server:
  port: 7070

spring:
  application:
    name: configserver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      username: nacos
      password: nacos
    config:
      server:
        git:
          uri: https://github.com/fangjian0423/blogimages
          search-paths: /